# exploring the central limit theorem in python...
# import random for printing random numbers...
import random

# importing plotly.express as pd..
# plotly.express is an built in module in python...
import plotly.express as px

# value for sample_size...
sample_size = 31

# value for sample_count...
sample_count = 1000

# central limit theorem, 1000 samples and each with 31... 
# random numbers between 0.0 and 0.1...
# formulate for x_values...
x_values = [(sum([random.uniform(0.0, 0.1)for i in range (sample_size)]) / \
            sample_size)
for _ in range(sample_count)]

# formulate for y_values...
y_values = [1 for _ in range(sample_count)]

# showing output with the help of show() paramete in python... 
px.histogram(x = x_values, y = y_values, nbins=20).show()