# calculating the probability of recovery between 15 and 21 days...
# importing norm from scipy.stats...
from scipy.stats import norm

# 18 days mean recovery with 1.5 std_dev
# value for mean...
mean = 18

# value for std_dev...
std_dev = 1.5

# 95% probability recovery time takes between 15 to 21 days...
# using CDF...
x = norm.cdf(21, mean, std_dev) - norm.cdf(15, mean, std_dev)

# prints x...
print(x)



# One-Tailed Test...
# python code for getting x-values with 5% of area behind it...
# importing norm from scipy.stats...
from scipy.stats import norm

# 18 days mean recovery with 1.5 std_dev
# value for mean...
mean = 18

# value for std_dev...
std_dev = 1.5

# using inverse of CDF...
# what is the x value has 5% area behind it?...
x = norm.ppf(.05, mean, std_dev)

# prints x... 
print(x)

# calculating the-tailed p-value...
# area of up to that 16-days mark is our p-value...
# importing norm from scipy.stats...
from scipy.stats import norm

# 18 days mean recovery with 1.5 std_dev
# value for mean...
mean = 18

# value for std_dev...
std_dev = 1.5

# using CDF...
# what is the x value has 5% area behind it?...
p_value = norm.cdf(16, mean, std_dev)

# prints x... 
print(p_value)



# Two-Tailed Test... 
# calculating a range for a statistical of 5%...
# importing norm from scipy.stats...
from scipy.stats import norm

# 18 days mean recovery with 1.5 std_dev
# value for mean...
mean = 18

# value for std_dev...
std_dev = 1.5

# using inverse of CDF...
# what is the x-value has 2.5% of area behind it?... 
x1 = norm.ppf(.025, mean, std_dev)

# what is the x-value has 97.5% of area behind it?... 
x2 = norm.ppf(.975, mean, std_dev)

# prints x1... 
print(x1)

# prints x2... 
print(x2)

# calculating the two-tailed p_values... 
# importing norm from scipy.stats...
from scipy.stats import norm

# 18 days mean recovery with 1.5 std_dev
# value for mean...
mean = 18

# value for std_dev...
std_dev = 1.5

# probability of 16 pr less days... 
p1 = norm.cdf(16, mean, std_dev)

# probability of 20 or more days... 
p2 = 1.0 - norm.cdf(20, mean, std_dev)

# p-values for both tails... 
p_value = p1 + p2

# prints p-values... 
print(p_value)