# calculating mean in python... 
# number of epts each person own...
sample = [1, 3, 2, 5, 7, 0, 2, 3]

# define forumla...
mean = sum(sample) / len(sample)

# print mean...
print(mean)

# calculating weighted mean in python...
# three exams of 0.20 weight each and final exam of . 40 weight... 
sample = [90, 80, 63, 87]
weight = [0.20, 0.20, 0.20, 0.40]

# define formula for a...
# multiplication of sample and weight and then add 1 by 1...
a = sum(s * w for s, w in zip(sample, weight)) 

# define formula for b...
# adds all values incremented in weight named object...
b = sum(weight)

# define formula for weighted_mean...
weighted_mean = a / b

# print weight_mean... 
print(weighted_mean)

# three exams of 0.20 weight each and final exam of . 40 weight... 
sample = [90, 80, 63, 87]
weight = [1.0, 1.0, 1.0, 2.0]

# define formula for a...
# multiplication of sample and weight and then add 1 by 1...
a = sum(s * w for s, w in zip(sample, weight)) 

# define formula for b...
# adds all values incremented in weight named object...
b = sum(weight)

# define formula for weighted_mean...
weighted_mean = a / b

# print weight_mean... 
print(weighted_mean)