# calculating median in python...
# number of pets each person owns... 
values = [0, 5, 1, 7, 10, 9, 14]

# makes an function name with values... 
#def median(values):
# sort values in ascending order and stored it in ordered named object...
ordered = sorted(values)

# len of values stored in n named object...
n = len(values)

# define formula for mid...
mid = int(n / 2) - 1 if n % 2 == 0 else int(n / 2)
    
# applies if-else condition...
# applied if condition...
if n % 2 == 0:
    
# print if statement...
    print((ordered[mid] + ordered[mid + 1]) / 2)      

# applied else condition...
else:
    
# print else statement...
    print(ordered[mid])