# calculating mode in python...
# import defaultdict from collections... 
from collections import defaultdict as dfd
# number of pets each person owns... 
values = [1, 3, 2, 7, 2, 9, 0, 2, 3]

# (lambda : 0) is an function that always returns 0...
counts = dfd(lambda : 0) 

# starts for loop...
for s in values:
    counts[s] += 1
    
# answering for max count values...
max_count = max(counts.values())

# define formula for modes...
modes = [v for v in set(values) if counts [v] == max_count]

# print modes...
print(modes)
