# the normal distribution CDF in python...
# importing norm(normal) from scipy.stats
from scipy.stats import norm

# Maybe you can take this values is in integer...
# value for mean...
mean = 64.43

# value for std_dev...
std_dev = 2.99

# define formula for CDF...
x = norm.cdf(64.43, mean, std_dev)

# print the value of x...
print(x)

# getting middle range probability using the CDF... 
# importing norm(normal) from scipy.stats
from scipy.stats import norm

# Maybe you can take this values is in integer...
# value for mean...
mean = 64.43

# value for std_dev...
std_dev = 2.99

# define formula for middle range probability...
x = norm.cdf(66, mean, std_dev) - norm.cdf(62, mean, std_dev) 

# print the value of x...
print(x)