# normal distribution function in python...
def normal_pdf(x : float, mean : float, std_dev : float) -> float:
    
# make variable for makes formula as easy and short...
# value for a...
    a = (2.0 * math.pi * std_dev ** 2)

# value for b...        
    b = (x - mean)
    
# value for c...    
    c = (2.0 * std_dev ** 2)
    
# return our created function...    
    return (1.0 / (a) ** 0.5) * math.exp(-1.0 * ((b) ** 2 / (c)))