# Pythagorean Triplet... 
# inputs value for a from user...
a = int(input('Enter value for a; '))

# inputs value for b from user...
b = int(input('Enter value for b; '))

# inputs value for c from user...
c = int(input('Enter value for b; '))

# applies if-else conditions...
# applied if condition...
if a*a + b*b == c*c:

# prints if statement...
    print(f"({a},{b},{c}); is an pythagorean triplet.")

# applied else condition...
else:        

# prints else statement...                
       print(f"({a},{b},{c}); is not an pythagorean triplet.")