# generating random number from normal distribution... 

# importing random...
import random

# importing norm(normal) from scipy.stats...
from scipy.stats import norm

# applies For-Loop...
for i in range(0, 1000):
    random_p = random.uniform(0.0, 1.0)
    random_weight = norm.ppf(random_p, loc=64.43, scale=2.99)
    print(random_weight)