# calculating standard variance for sample in python...
# import sqrt(square-root) from math...
from math import sqrt

# number of pets each person owns... 
values = [0, 1, 5, 7, 9, 10, 14]

# makeing def function for storing values named variable data...
def variance(values, is_sample: bool = False):
    
# define mean formula...    
    mean = sum(values) / len(values)
    
# define formula for variance...
# 1st.variance = sum((v - mean) * (v - mean) for v in values) / len(values) 
# you can be use 1st.variance named formula...
    variance = sum((v - mean) ** 2 for v in values) / (len(values) - (1 if is_sample else 0))
      
# return value of variance...   
    return variance
    
# prints variance for sample... 
print("VARIANCE = {}".format(variance(values, is_sample = True)))    

# calculating standard deviation for sample in python...
# import sqrt(square-root) from math...
from math import sqrt

# number of pets each person owns... 
values = [0, 1, 5, 7, 9, 10, 14]

# makeing def function for storing values named variable data...
def variance(values, is_sample: bool = False):
    
# define mean formula...    
    mean = sum(values) / len(values)
    
# define formula for variance...
# 1st.variance = sum((v - mean) * (v - mean) for v in values) / len(values) 
# you can be use 1st.variance named formula...
    variance = sum((v - mean) ** 2 for v in values) / (len(values) - (1 if is_sample else 0))
      
# return value of variance...   
    return variance

# making def std_dev (standard-deviation) function for returning variance in square-root...
def std_dev(values, is_sample: bool = False):
    
# returns square-root of varianc... 
    return sqrt(variance(values,  is_sample))

# prints standard-deviation for sample...
print("STANDARD DERIVATION = {}".format(std_dev(values, is_sample = True)))