# Getting a critical value range with T-distribution... 
# importing t from scipy.stats... 
from scipy.stats import t

# get critical value range for 95% confidence with a simple size of 25

# use inverse of CDF...
# value for n... 
n = 25

# value for lower... 
lower = t.ppf(.025, df = n-1)

# value for upper... 
upper = t. ppf(.975, df = n-1)

# prints lower and upper... 
print(lower, upper)