# calculating variance in python... 
# number of pets each person owns... 
values = [0, 1, 5, 7, 9, 10, 14]

# make def function for storing values named variable data...
def variance(values):
    
# define mean formula...    
    mean = sum(values) / len(values)
    
# define formula for variance...
# 1st.variance = sum((v - mean) * (v - mean) for v in values) / len(values) 
# you can be use 1st.variance named formula...
    variance = sum((v - mean) ** 2 for v in values) / len(values)
      
# return value of variance...   
    return variance

# print variance...
print(variance(values))

# calculating standard deviation in python
# import sqrt(square-root) from math...
from math import sqrt

# number of pets each person owns... 
values = [0, 1, 5, 7, 9, 10, 14]

# makeing def function for storing values named variable data...
def variance(values):
    
# define mean formula...    
    mean = sum(values) / len(values)
    
# define formula for variance...
# 1st.variance = sum((v - mean) * (v - mean) for v in values) / len(values) 
# you can be use 1st.variance named formula...
    variance = sum((v - mean) ** 2 for v in values) / len(values)
      
# return value of variance...   
    return variance

# making def std_dev (standard-deviation) function for returning variance in square-root...
def std_dev(values):
    
# returns square-root of varianc3      
    return sqrt(variance(values))

# prints standard-deviation ...
print(std_dev(values))