# turn Z-scores into x-values and vice versa...
# make z_score named function... 
def z_score(x, mean, std_dev):

# return formula...       
    return (x - mean) / std_dev
   
# make z_to_x named function...      
def z_to_x(z, mean, std_dev):

# return formula...      
   return (z * std_dev) + mean

# value for mean...       
mean = 140000

# value for std_dev...
std_dev = 3000

# value for x...
x = 150000

# define z_score for z and it's variables...
z = z_score(x, mean, std_dev)

# define z_to_x for back_to_x and it's variables...
back_to_x = z_to_x(z, mean, std_dev)

# prints z_score...
print("Z-Score: {}".format(z))     

# prints back_to_x...   
print("Back To X: {}".format(back_to_x))    

# coefficient of variation...
# value for mean...       
mean = 140000

# makes variable for mean as m...
m = mean

# value for std_dev...
std_dev = 3000

# makes variable for std_dev for s...
s = std_dev

# makes coefficient_of_variation named function...
def coefficient_of_variation(mean, std_dev):

# return s / m...        
    return s / m

# prints coefficient of variation...
print("Coefficient Of Variation: {}".format(s / m))                                                                                                                                                                                                                                                      